name: MongoDB CRUD Tests

on: [push]

env:
  NODE_ENV: production
  DOTENV_FILE: .env.ci

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: --name mongodb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Copy .env.ci to .env
        run: cp $DOTENV_FILE .env

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test