name: GitHub Actions Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing Dependencies
        run: npm install
      - name: Build project
        run: nest build
      - name: Testing project e2e
        run: npm run test:e2e
     

      