name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Dependencies
        run: npm ci

      - name: Move .env.ci to .env
        run: mv .env.ci .env
  
      - name: Start MongoDB
        run: docker-compose -f docker-compose.yml up -d
  
      - name: Run end-to-end tests
        run: npm run test:e2e