name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Dependencies
        run: npm ci

      - name: Move .env.ci to .env
        run: mv .env.ci .env
  
      - name: Run unit tests
        run: npm run test